apiVersion: apps/v1
kind: Deployment
metadata:
  name: rss-to-email-dep
  namespace: rte-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rss-to-email
  template:
    metadata:
      labels:
        app: rss-to-email
    spec:
      containers:
      - name: rss-to-email-con
        image: rss-to-email:latest
        imagePullPolicy: Never
        ports:
            - containerPort: 9000
              protocol: TCP
---

---
apiVersion: v1
kind: Service
metadata:
  name: rss-to-email-svc
  namespace: rte-ns
spec:
  type: NodePort
  selector:
    app: rss-to-email
  ports:
    - name: http
      protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 31900
    