FROM openjdk:11.0.13-buster

WORKDIR /opt/docker
COPY --chown=daemon:root opt /opt

EXPOSE 9000
USER daemon
# https://www.kaspersky.com/blog/log4shell-critical-vulnerability-in-apache-log4j/43124/
ENV LOG4J_FORMAT_MSG_NO_LOOKUPS true
ENV RUNTIME_ENV "docker"
ENV JAVA_OPTS="-Xms100M -Xmx758M -XX:+UseG1GC -XX:+UseStringDeduplication"
ENTRYPOINT ["/opt/docker/bin/newssnips-webapp"]
CMD []

