FROM gcr.io/datamechanics/spark:jvm-only-3.1.1-hadoop-3.2.0-java-11-scala-2.12-latest

WORKDIR /tmp
RUN wget https://dlcdn.apache.org/spark/spark-3.1.2/spark-3.1.2-bin-hadoop3.2.tgz -O spark.tgz
RUN tar xvf spark.tgz && \
  rm -rf ${SPARK_HOME}/* && \
  mv spark-3.1.2-bin-hadoop3.2/* $SPARK_HOME && \
  rm -rf spark.tgz

WORKDIR /opt/docker

COPY --chown=daemon:root 2/opt /opt
COPY --chown=daemon:root 4/opt /opt
COPY --chown=daemon:root scripts/docker-entrypoint.sh /opt/entrypoint.sh

USER daemon
ENV RUNTIME_ENV "docker"
ENV TF_CPP_MIN_LOG_LEVEL 2

ENV JAVA_OPTS="-Xms1024M -Xmx7048M -XX:+UseG1GC -XX:+UseStringDeduplication"
ENTRYPOINT ["/opt/entrypoint.sh"]
CMD []

