apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master-dep
  namespace: rte-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-master
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      containers:
        - name: spark-master-con
          image: bitnami/spark:3.1.2
          # command: ["start-all.sh"]
          ports:
            - containerPort: 7077
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: "700Mi"
              cpu: "1"
            limits:
              memory: "700Mi"
              cpu: "1"

---
apiVersion: v1
kind: Service
metadata:
  name: spark-master-svc
  namespace: rte-ns
spec:
  selector:
    app: spark-master
  ports:
    - name: dashboard-port
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: master-port
      protocol: TCP
      port: 7077
      targetPort: 7077

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker-dep
  namespace: rte-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-worker
  template:
    metadata:
      labels:
        app: spark-worker
    spec:
      containers:
        - name: spark-worker-con
          image: bitnami/spark:3.1.2
          command: ["start-worker.sh", "spark://spark-master-svc.rte-ns.svc.cluster.local:7077"]
          resources:
            requests:
              memory: "700Mi"
              cpu: "1"
            limits:
              memory: "700Mi"
              cpu: "1"
 