package fyi.newssnips.datacruncher

object FeedUrls {
  // TODO move to comment friendly format. e.g. yaml
  val categoryToUrls: Map[String, Seq[String]] = Map(
    // google news keyword rss: https://www.aakashweb.com/articles/google-news-rss-feed-url/
    "world" -> Seq(
      "https://feeds.a.dj.com/rss/RSSWorldNews.xml",
      "https://www.reddit.com/r/UpliftingNews/.rss",
      "https://www.reddit.com/r/worldnews/.rss",
      "http://rss.cnn.com/rss/cnn_world.rss",
      "http://rss.cnn.com/rss/cnn_us.rss",
      "http://rss.cnn.com/rss/cnn_latest.rss",
      "https://nypost.com/feed",
      "http://feeds.feedburner.com/zerohedge/feed",
      "https://www.huffpost.com/section/front-page/feed?x=1",
      "http://feeds.foxnews.com/foxnews/latest",
      "http://feeds.foxnews.com/foxnews/world",
      "https://cdn.feedcontrol.net/8/1114-wioSIX3uu8MEj.xml",
      "https://www.yahoo.com/news/rss",
      "https://www.rt.com/rss/news/",
      "https://www.investing.com/rss/news.rss",
      "https://api.axios.com/feed/",
      "https://www.washingtontimes.com/rss/headlines/news/",
      "https://www.washingtontimes.com/rss/headlines/news/world/",
      "https://slate.com/feeds/all.rss",
      "https://www.ft.com/world?format=rss",
      "https://www.ft.com/home-beta?format=rss",
      "https://www.chicagotribune.com/arcio/rss/category/news/breaking/",
      "https://www.aljazeera.com/xml/rss/all.xml",
      "https://cms.qz.com/feed/",
      "https://feeds.mcclatchy.com/sacbee/sections/news/nation-world/stories",
      "https://feeds.mcclatchy.com/sacbee/sections/news/nation-world/world/stories",
      "https://www.standard.co.uk/news/world/rss",
      "http://feeds.skynews.com/feeds/rss/world.xml",
      "http://feeds.feedburner.com/motherjones/feed",
      "https://www.seattletimes.com/feed/",
      "https://www.cbsnews.com/latest/rss/world",
      "https://news.google.com/rss",
      "https://news.google.com/rss/topics/CAAqJggKIiBDQkFTRWdvSUwyMHZNRGx1YlY4U0FtVnVHZ0pWVXlnQVAB",
      "https://www.upworthy.com/feeds/feed.rss",
      "https://feeds.npr.org/1001/rss.xml",
      "https://feeds.npr.org/1004/rss.xml",
      "https://www.express.co.uk/posts/rss/78/world"
    ),
    "markets" -> Seq(
      "https://news.google.com/rss/topics/CAAqJggKIiBDQkFTRWdvSUwyMHZNRGx6TVdZU0FtVnVHZ0pWVXlnQVAB?hl=en-US&gl=US&ceid=US%3Aen&oc=11",
      "https://news.google.com/rss/topics/CAAqJggKIiBDQkFTRWdvSUwyMHZNRGx6TVdZU0FtVnVHZ0pWVXlnQVAB/sections/CAQiSENCQVNNQW9JTDIwdk1EbHpNV1lTQW1WdUdnSlZVeUlQQ0FRYUN3b0pMMjB2TUdkbWNITXpLZ3NTQ1M5dEx6Qm5abkJ6TXlnQSoqCAAqJggKIiBDQkFTRWdvSUwyMHZNRGx6TVdZU0FtVnVHZ0pWVXlnQVABUAE?hl=en-US&gl=US&ceid=US%3Aen&oc=11",
      "https://news.google.com/rss/topics/CAAqJggKIiBDQkFTRWdvSUwyMHZNRGx6TVdZU0FtVnVHZ0pWVXlnQVAB/sections/CAQiXENCQVNQd29JTDIwdk1EbHpNV1lTQW1WdUdnSlZVeUlQQ0FRYUN3b0pMMjB2TURsNU5IQnRLaG9LR0FvVVRVRlNTMFZVVTE5VFJVTlVTVTlPWDA1QlRVVWdBU2dBKioIAComCAoiIENCQVNFZ29JTDIwdk1EbHpNV1lTQW1WdUdnSlZVeWdBUAFQAQ?hl=en-US&gl=US&ceid=US%3Aen&oc=11",
      "https://news.google.com/rss/topics/CAAqJggKIiBDQkFTRWdvSUwyMHZNRGx6TVdZU0FtVnVHZ0pWVXlnQVAB/sections/CAQiRkNCQVNMZ29JTDIwdk1EbHpNV1lTQW1WdUdnSlZVeUlPQ0FRYUNnb0lMMjB2TURKdWQzRXFDaElJTDIwdk1ESnVkM0VvQUEqKggAKiYICiIgQ0JBU0Vnb0lMMjB2TURsek1XWVNBbVZ1R2dKVlV5Z0FQAVAB?hl=en-US&gl=US&ceid=US%3Aen&oc=11",
      "http://feeds.marketwatch.com/marketwatch/realtimeheadlines/",
      "https://www.standard.co.uk/business/economy/rss",
      "https://www.standard.co.uk/business/markets/rss",
      "https://www.ft.com/markets?format=rss",
      "https://slate.com/feeds/business.rss",
      "https://finance.yahoo.com/news/rss",
      "https://www.nasdaq.com/feed/rssoutbound",
      "https://seekingalpha.com/market_currents.xml",
      "https://seekingalpha.com/feed.xml",
      "http://feeds.feedburner.com/TradingVolatility",
      "http://rss.politico.com/economy.xml",
      "https://feeds.a.dj.com/rss/RSSMarketsMain.xml",
      "http://thehill.com/taxonomy/term/30/feed",
      "http://thehill.com/taxonomy/term/20/feed",
      "https://nypost.com/business/feed/",
      "http://feeds.skynews.com/feeds/rss/business.xml",
      "http://feeds.marketwatch.com/marketwatch/topstories/",
      "https://www.investing.com/rss/investing_news.rss",
      "https://www.investing.com/rss/stock.rss",
      "https://www.washingtonexaminer.com/tag/economy.rss",
      "https://www.washingtontimes.com/rss/headlines/news/business-economy/",
      "http://feeds.benzinga.com/benzinga/best-of-benzinga",
      "https://www.benzinga.com/top-stories/feed",
      "https://www.benzinga.com/economics/feed",
      "https://www.marketscreener.com/rss/FeedNews.php",
      "https://www.seattletimes.com/business/feed/",
      "https://www.cbsnews.com/latest/rss/moneywatch",
      "https://www.reddit.com/r/dogecoin/.rss",
      "https://www.reddit.com/r/CryptoCurrency/.rss",
      "https://www.reddit.com/r/Superstonk/.rss",
      "https://www.reddit.com/r/amcstock/.rss",
      "https://www.reddit.com/r/Bitcoin/.rss",
      "https://www.reddit.com/r/investing/.rss",
      "https://www.reddit.com/r/SPACs/.rss",
      "https://www.reddit.com/r/options/.rss",
      "https://www.express.co.uk/posts/rss/21/finance",
      "https://www.barchart.com/news/rss/financials/crypto",
      "https://www.barchart.com/news/authors/rss",
      "https://www.barchart.com/news/rss/financials",
      "https://www.barchart.com/news/rss/commodities",

      // https://tradingeconomics.com/rss/ (see other useful)
      // "https://tradingeconomics.com/rss/news.aspx", (generic headline for every country. e.g. GDP)
      // "https://tradingeconomics.com/united-states/rss",

      "https://www.fool.com/a/feeds/foolwatch?format=rss2&id=foolwatch&apikey=foolwatch-feed",
      "https://www.cnbc.com/id/20409666/device/rss/rss.html?x=1",
      "https://www.wallstreetsurvivor.com/feed/",
      "https://www.investing.com/rss/news_25.rss",
      "https://www.reddit.com/r/StockMarket/.rss",
      "https://www.reddit.com/r/wallstreetbets/.rss",
      "https://www.reddit.com/r/stocks/.rss",
      "https://feeds.npr.org/1006/rss.xml"
    ),
    // "technology" -> Seq("https://www.techmeme.com/feed.xml"),
    "politics" -> Seq(
      "https://feeds.npr.org/1014/rss.xml",
      "https://rss.politico.com/congress.xml",
      "http://thehill.com/rss/syndicator/19110",
      "https://www.memeorandum.com/feed.xml",
      "https://www.reddit.com/r/politics/.rss",
      "https://www.reddit.com/r/NeutralPolitics/.rss",
      "https://news.yahoo.com/rss/politics",
      "https://www.washingtonexaminer.com/tag/politics.rss",
      "https://www.nationalreview.com/feed/",
      "https://fivethirtyeight.com/politics/feed/",
      "https://www.politifact.com/rss/all/",
      "https://www.politifact.com/rss/factchecks/",
      "https://www.washingtontimes.com/rss/headlines/news/politics/",
      "https://slate.com/feeds/news-and-politics.rss",
      "https://www.rollingstone.com/politics/feed/",
      "https://www.chicagotribune.com/arcio/rss/category/politics/",
      "http://feeds.feedburner.com/realclearpolitics/qlMj",
      "https://www.benzinga.com/topic/government/feed",
      "https://feeds.mcclatchy.com/sacbee/sections/news/politics-government/stories",
      "https://www.defenseone.com/rss/all/",
      "http://feeds.skynews.com/feeds/rss/politics.xml",
      "https://www.motherjones.com/politics/feed/",
      "https://www.cbsnews.com/latest/rss/politics"
    ),
    "entertainment" -> Seq(
      /*
      needs rss: https://coed.com/category/viral/
       */
      "https://news.google.com/rss/topics/CAAqJggKIiBDQkFTRWdvSUwyMHZNREpxYW5RU0FtVnVHZ0pWVXlnQVAB?hl=en-US&gl=US&ceid=US%3Aen&oc=11",
      "https://news.google.com/rss/topics/CAAqJggKIiBDQkFTRWdvSUwyMHZNREpxYW5RU0FtVnVHZ0pWVXlnQVAB/sections/CAQiRkNCQVNMZ29JTDIwdk1ESnFhblFTQW1WdUdnSlZVeUlPQ0FRYUNnb0lMMjB2TURGeVpub3FDaElJTDIwdk1ERnlabm9vQUEqKggAKiYICiIgQ0JBU0Vnb0lMMjB2TURKcWFuUVNBbVZ1R2dKVlV5Z0FQAVAB",
      "https://news.google.com/rss/topics/CAAqJggKIiBDQkFTRWdvSUwyMHZNREpxYW5RU0FtVnVHZ0pWVXlnQVAB/sections/CAQiRkNCQVNMZ29JTDIwdk1ESnFhblFTQW1WdUdnSlZVeUlPQ0FRYUNnb0lMMjB2TURSeWJHWXFDaElJTDIwdk1EUnliR1lvQUEqKggAKiYICiIgQ0JBU0Vnb0lMMjB2TURKcWFuUVNBbVZ1R2dKVlV5Z0FQAVAB?hl=en-US&gl=US&ceid=US%3Aen&oc=11",
      "https://news.google.com/rss/topics/CAAqJggKIiBDQkFTRWdvSUwyMHZNREpxYW5RU0FtVnVHZ0pWVXlnQVAB/sections/CAQiWkNCQVNQUW9JTDIwdk1ESnFhblFTQW1WdUdnSlZVeUlPQ0FRYUNnb0lMMjB2TURKMmVHNHFHUW9YQ2hOTlQxWkpSVk5mVTBWRFZFbFBUbDlPUVUxRklBRW9BQSoqCAAqJggKIiBDQkFTRWdvSUwyMHZNREpxYW5RU0FtVnVHZ0pWVXlnQVABUAE?hl=en-US&gl=US&ceid=US%3Aen&oc=11",
      "https://www.seattletimes.com/entertainment/feed/",
      "https://www.standard.co.uk/culture/film/rss",
      "https://www.cbsnews.com/latest/rss/entertainment",
      "https://www.mic.com/rss",
      "https://www.standard.co.uk/culture/music/rss",
      "https://www.standard.co.uk/culture/comedy/rss",
      "https://www.motherjones.com/media/feed/",
      "https://www.express.co.uk/posts/rss/79/celebritynews",
      "https://www.buzzfeed.com/celebrity.xml",
      "http://feeds.skynews.com/feeds/rss/entertainment.xml",
      "https://www.buzzfeed.com/tvandmovies.xml",
      "http://syndication.eonline.com/syndication/feeds/rssfeeds/topstories.xml",
      "https://meredith.mediaroom.com/news-releases?pagetemplate=rss&category=816",
      "https://www.express.co.uk/posts/rss/18/entertainment",
      // "http://feeds.bet.com/AllBetcom", stale data and posts.
      "https://www.hollywoodintoto.com/feed/",
      "https://hollywoodlife.com/feed/",
      "https://mtonews.com/.rss/full/",
      "http://feeds.feedburner.com/variety/headlines",
      "https://www.reddit.com/r/celebrities/.rss",
      "https://www.reddit.com/r/entertainment/.rss",
      "https://www.wesmirch.com/feed.xml",
      "https://mediagazer.com/feed.xml",
      "https://www.yahoo.com/entertainment/rss",
      "https://www.rollingstone.com/music/feed/",
      "https://www.rollingstone.com/tv/feed/",
      "https://www.rollingstone.com/movies/feed/",
      "https://www.reddit.com/r/marvelstudios/.rss",
      "https://www.reddit.com/r/StarWars/.rss",
      "https://www.reddit.com/r/MovieDetails/.rss",
      "https://www.reddit.com/r/DC_Cinematic/.rss",
      "https://www.chicagotribune.com/arcio/rss/category/entertainment/",
      "https://www.hollywoodreporter.com/t/awards/feed/",
      "https://www.hollywoodreporter.com/c/news/feed/",
      "https://www.hollywoodreporter.com/c/movies/feed/",
      "https://www.hollywoodreporter.com/c/tv/feed/",
      "https://www.hollywoodreporter.com/t/international/feed/",
      "https://feeds.mcclatchy.com/sacbee/sections/entertainment/movies-news-reviews/stories",
      "https://feeds.mcclatchy.com/sacbee/sections/entertainment/music-news-reviews/stories"
    )
  )
}
